version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pulseflow
      POSTGRES_PASSWORD: changeme_local_dev_only
      POSTGRES_MULTIPLE_DATABASES: pulseflow_identity,pulseflow_queue
    ports:
      - "5432:5432"
    volumes:
      - pulseflow_postgres_data:/var/lib/postgresql/data
      - ./infra/init-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multiple-postgres-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulseflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  identity-service:
    build:
      context: ./services/identity-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: pulseflow
      DB_PASSWORD: changeme_local_dev_only
      DB_NAME: pulseflow_identity
      DB_SYNCHRONIZE: "true"
      JWT_ACCESS_SECRET: local_dev_access_secret_change_me
      JWT_REFRESH_SECRET: local_dev_refresh_secret_change_me
    depends_on:
      postgres:
        condition: service_healthy

  queue-service:
    build:
      context: ./services/queue-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: pulseflow
      DB_PASSWORD: changeme_local_dev_only
      DB_NAME: pulseflow_queue
      DB_SYNCHRONIZE: "true"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pulseflow_postgres_data:
